config/routes.rb
Rails.application.routes.draw do
  root "lists#index"

  # get "/lists", to: "lists#index"
  # get 'cards/index'


  resources :lists
  resources :cards

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/list.rb
class List < ApplicationRecord
    has_many :cards
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card
    else
      render :new
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])

    if @card.update(card_params)
      redirect_to @card
    else
      render :edit
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    redirect_to root_path
  end

  private
    def card_params
      params.require(:card).permit(:name, :description, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.includes(:cards).all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(name: params[:list][:name])

    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update(name: params[:list][:name])
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/cards/_form.html.erb
<%= form_with model: card do |form| %>
  <%= form.collection_select :list_id, List.order(:name), :id, :name %>


  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% card.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% card.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Edit Card</h1>

<%= render "form", card: @card %>

app/views/cards/index.html.erb
<h1>Cards#index</h1>
<p>Find me in app/views/cards/index.html.erb</p>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= form_with model: @card do |form| %>
  <%= form.collection_select :list_id, List.order(:name), :id, :name %>


  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @card.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% @card.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/show.html.erb
<h1><%= @card.name %></h1>

<%= link_to "Edit", edit_card_path(@card) %>
<%= link_to "delete", card_path(@card),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>

<p><%= @card.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with model: list do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% list.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render "form", list: @list %>

app/views/lists/index.html.erb
<h1>Lists#index</h1>

<ul>
  <% @lists.each do |list| %>
    <li>
      <%= list.name %> (<%= link_to "edit", edit_list_path(list) %>)
      (<%= link_to "delete", list_path(list),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>)

      <ul>
        <% list.cards.each do |card| %>
          <li><%= link_to card.name, card_path(card) %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<%= link_to "New List", new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= form_with model: @list do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @list.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>